server:
  port: 8904
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/
  instance:
    instance-id: demo-application

spring:
  application:
    name: demo-application