eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/
      prefer-ip-address: true
  instance:
    hostname: gateway-service

server:
  port: 8902

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: demo-application
              uri: lb://demo-application
              predicates:
                - Path=/app/**

  main:
    web-application-type: reactive