server:
  port: 8901  #???

spring:
  application:
    name: discovery-eureka    #??

eureka:
  instance:
    hostname: localhost   #host??????
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:   #????
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

