server:
  port: 8903
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/
  instance:
    instance-id: user-service
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/nan
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect